version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth_service_app
    environment:
      CONFIG_PATH: /app/config.yml
    volumes:
      - ./config.yml:/app/config.yml
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: auth_service_db
    environment:
      POSTGRES_USER: USER
      POSTGRES_PASSWORD: PASSWORD
      POSTGRES_DB: auth_service
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
