version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth_service_app
    environment:
      CONFIG_PATH: /app/configs/config.yaml
    volumes:
      - ./config.yml:/app/configs/config.yaml
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - auther_network

  db:
    image: postgres:latest
    container_name: auth_service_db
    environment:
      POSTGRES_USER: USER
      POSTGRES_PASSWORD: PASSWORD
      POSTGRES_DB: auth_service
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - auther_network

volumes:
  pgdata:

networks:
  auther_network:
    driver: bridge
